name: Build and Release Web

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Read version from package.json
        id: get_version
        shell: bash
        run: |
          VERSION=$(node -p "JSON.parse(require('fs').readFileSync('package.json','utf-8')).version")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build
        env:
          NODE_ENV: production
        run: npm run build

      - name: Package dist
        run: |
          cd dist
          zip -r ../immersive-clock-${{ steps.get_version.outputs.version }}.zip .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Immersive Clock v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            immersive-clock-${{ steps.get_version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}